---
title: "Dissemination"
output: distill::distill_article
---

### Expert Advisory

__Member of expert network, Transparency International Denmark__

* In May 2021, I was invited to join Transparency International Denmark’s network of Danish researchers who have expertise related to corruption and abuse of power. Description in Danish [here](https://transparency.dk/kontakt/ekspertgruppe/).

<p>


### Usage as expert source
__Radio4, March 14, 2023__

* Interviewed about Danish MPs' salaries and pensions, and why they are important for our democracy, but difficult to change. Listen [here](https://www.radio4.dk/program/ring-til-due/?gid=49189&title=ring-til-radio4-skal-kvinder-have-lov-til-at-bade-topls-i-de-danske-svmmehaller&time=3453) (in Danish).


__Avisen Danmark, Aarhus Stifttidende and Fyns Amts Avis, October 28, 2022__

* Expert source about politicians salaries and the economic returns of having a political career. Danish URL [here](https://avisendanmark.dk/artikel/nogle-tjener-p%C3%A5-at-g%C3%A5-ind-i-politik-men-langt-fra-alle-jeg-gik-20-000-ned-i-l%C3%B8n-om-m%C3%A5neden)

__DR P1 Orientering, June 14, 2022__

* I was interviewed in the news program Orientering on the nationwide Danish radio station P1 about politicians' careers, party switching and political representation. Starts from 56:25 [here](https://www.dr.dk/lyd/p1/orientering/orientering-2022-06-14) (in Danish).

__Avisen Danmark, Aarhus Stifttidende and Fyns Amts Avis, May 3, 2022__

* Expert source about revolving door employmets and the public's truft in politicians as a Danish minister left politics for a job as lobbyist. Danish URL [here](https://avisendanmark.dk/artikel/h%C3%A6kkerups-jobskifte-genopliver-krav-om-karant%C3%A6ne-til-politikere-han-mister-trov%C3%A6rdighed-hvis-han-nu-kommer-og-siger-at-regeringens-sundhedsudspil-er-dumt)

<p>

### Dissemination of research in media

__Politiken, June 29, 2021: ”Pia overbeviser ligeså godt som Per, når hun udtaler sig som ekspert”__ with Katrine Greve-Poulsen, Rasmus Tue Pedersen and Erik Albæk.

* Article disseminating the results of our research article ”No Gender Bias in Audience Perceptions of Male and Female Experts in the News: Equally Competent and Persuasive” in the Danish newspaper Politiken.
* Danish URL [here](https://politiken.dk/debat/debatindlaeg/art8259934/Pia-overbeviser-liges%C3%A5-godt-som-Per-n%C3%A5r-hun-udtaler-sig-som-ekspert)

__Uniavisen/The University Post, June 25, 2021: ”New study: Readers perceive male and female experts as equally competent”.__

* My co-author Katrine Greve-Poulsen and I were interviewed about our first academic publication by University of Copenhagen’s independent news paper Uniavisen (The University Post).
* English version [here](https://uniavisen.dk/en/new-study-readers-perceive-male-and-female-experts-as-equally-competent/), Danish version [here](https://uniavisen.dk/ny-undersoegelse-laesere-finder-mandlige-og-kvindelige-eksperter-lige-kompetente/).

<p>

### Research Presentations to Non-Academics
__Research presentation, Transparency International Denmark__, May 2021

* Presentation about my research field for the board of Transparency
International Denmark. Further, I provided my inputs and discussed how to mitigate corruption and malfeasance in the Danish municipalities in relation to the (at that point) upcoming Danish municipal election in November 2021.

__Research presentation at Projekt Forskerspirer__, April 2021

* Presentation about my research and reseach designs broadly for the social science section in Projekt Forskerspirer (Junior Researchers Project) – a program where academically talented high school students conduct their own research.

