---
title: "Research"
output: distill::distill_article
---


<!--Here you can see my research -- published articles (yeah alright, there is only one for now) as well as stuff I am currently working on.

If you want a copy of one of my working papers please reach out to me at **fkl *[at]* ifs.ku.dk**.-->



### Published and accepted work

__The Gendered Cost of Politics__ with Lene Holm Pedersen. Accepted in *British Journal of Political Science*.

<!--* We investigate political candidates' preferences for different job attributes of holding office using a conjoint-choice experiment fielded among the political candidates in the Danish municipal election in November 2021.-->

<p>

__Reward or Punishment? The Distribution of Life-Cycle Returns to Political Office__ with Jens Olav Dahlgaard and Nicolai Kristensen. *Political Science Research & Methods*, published online 2025: 1-9. [URL](https://www.cambridge.org/core/journals/political-science-research-and-methods/article/reward-or-punishment-the-distribution-of-lifecycle-returns-to-political-office/9D15D43DAF4D7BCA1AE469E4E1BC0DE7)


<!--* We estimate the economic returns to winning office focusing on close winning and losing candidates running for Danish national elections. We devote special attention to 1) effect heterogeneity among candidates with different pre-office income potentials and 2) the timing of returns to office, as some economic consequences of holding office occur immediately when entering office while others occur later in life.-->

<p>


__What Happens When Women Win Elections? The Electoral Returns to Increased Representation of Women__ with Benjamin Egerod, Lene Holm Pedersen and Jens Olav Dahlgaard. *Journal of Politics*, published online 2024: 1-11. [URL](https://www.journals.uchicago.edu/doi/abs/10.1086/734266?journalCode=jop)

<!--* We investigate if the election of a woman for office foster female representation in future elections and beyond the candidate herself. We do this by focusing on local elections, where a woman marginally wins a seat over a man competing for the same seat, and estimate what this means to the composition of the future candidate pools and thus how it shapes the supply of political candidates.-->

<p>

**No Gender Bias in Audience Perceptions of Male and Female Experts in the News: Equally Competent and Persuasive**. *The International Journal of Press/Politics* with Katrine Greve-Poulsen, Rasmus T. Pedersen & Erik Albæk, 2021, 28 (1), 116-137. [URL](https://journals.sagepub.com/doi/abs/10.1177/19401612211025499), [Open Access version](https://portal.findresearcher.sdu.dk/en/publications/no-gender-bias-in-audience-perceptions-of-male-and-female-experts), [Code and replication data](https://t.co/VNDcuQ8Lnz).


### Work in progress 


__Government Ideology and Gender Equality in Public Sector Career Progression__ with Lasse Aaskoven and Benjamin Egerod. Revise and resubmit in *Political Science Research & Methods*

<!--* Relying on granular data of the universe of Danish civil servants, we estimate how women’s career progression in the Danish bureaucracy depend on the ideology of the government in office.-->


<p> 

__The Career Rewards of Being Part-time Politician__

<!--* I estimate how holding a part-time political office affect income and civil career of Danish local councilors. Concerning the latter, I specifically investigate what being a local councilor do to the councilors labour supply and probability of being promoted in their outside job.-->

<p>

__The Gender of a Big Spender? The Causal Effect of Women on Agenda-Setting, Public Budgeting and Expenditures__ with Karl-Emil Svenningsen Bendtsen & Lene Holm Pedersen. Under review.

<p>

__The Effects of Electing Working Class Candidates__ with Olivia Levinsen, Anna Lund & Frederik Hjorth.

<p>

__Male Managers and the Promotion of Women in Public Service__ with Lasse Aaskoven & Benjamin Egerod.

<p>

__Cherries on Top? The Effect of Ballot Ordering__ with Olivia Levinsen, Anna Lund Sørensen & Frederik Hjorth.

<p>

__Proximity to Parliament: The Representational Effects of Politicians' Costs of Commuting__ with Frederik Hjorth.

### Work in Danish

__Stabil Politisk Tillid Trods Minksag og Coronapandemi__ with Rune Stubager. English: Stable Political Trust Despite Mink Case and Corona Pandemic.
Book chapter in _Partiledernes Kamp Om Midten_ (ed. Kasper M. Hansen & Rune Stubager), a book examining the Danish Election 2022.
